site_name: My Docs

# 主题配置
theme:
  name: material
  # 设置站点语言为英文
  language: en
  palette:
    # 浅色模式
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色模式
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

# 额外配置
extra:
  # 多语言切换配置
  alternate:
    - name: 中文
      link: ../zh/
      lang: zh
